version: '3.8'

services:
  saint-prediction-model-trainer:
    image: saint-prediction-model-trainer
    container_name: saint-prediction-model-trainer
    hostname: saint-prediction-model-trainer
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - S3_ENDPOINT=${S3_ENDPOINT}
      - SAINT_ANALYTICS_DB_CONNECTION_STRING=${SAINT_ANALYTICS_DB_CONNECTION_STRING}
      - SAINT_ANALYTICS_DB_SAINT_MARTYRED_FACT_TABLE_NAME=${SAINT_ANALYTICS_DB_SAINT_MARTYRED_FACT_TABLE_NAME}
    ports:
      - 4567:80

networks:
  default:
    external: true
    name: local-network
